name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main     # Hoặc nhánh chính của bạn
      - dev  # Hoặc nhánh thứ 2

# THÊM ĐOẠN PERMISSIONS NÀY VÀO
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine Target Directory
        id: branch-dir
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "dir=production" >> $GITHUB_OUTPUT
          else
            echo "dir=preview-${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          destination_dir: ${{ steps.branch-dir.outputs.dir }}
          keep_files: true   # <--- THÊM DÒNG NÀY ĐỂ KHÔNG BỊ XÓA MẤT THƯ MỤC CỦA NHÁNH KIA
